version: '3'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - REACT_APP_API_PREFIX=/api
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
  worker:
    build:
      context: worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
    depends_on:
      - client
      - api
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis'
